fix runVDR filetype from link to script
This did cause problems when checking out on filesystems
with limited path length like XFS:
/space> git checkout .
error: unable to create symlink tdt/cvs/cdk/root/usr/local/bin/runVDR (File name too long)
(and I wonder if it did work correctly at all...)